import z from "zod";

export enum LEAD_STATUS {
    NEW_LEAD = "NEW_LEAD",
    ATTEMPTED_TO_CONTACT = "ATTEMPTED_TO_CONTACT",
    CONTACTED = "CONTACTED",
    QUALIFIED = "QUALIFIED",
    UNQUALIFIED = "UNQUALIFIED",
}

export const ZLEAD_STATUS = z.nativeEnum(LEAD_STATUS);
